#!/usr/bin/env bash
# agent-lifecycle-skills — install or update /spec and /wrap in a project.
# https://github.com/imanassi/agent-lifecycle-skills
#
#   ./install.sh          /path/to/project     first install
#   ./install.sh --update /path/to/project     pull in a newer version
#   ./install.sh --update --dry-run /path/to/project
#
# Install creates what is missing and never touches what is already there.
#
# Update is conservative: it refreshes files you have not edited, and for files
# you HAVE edited it leaves yours alone and drops the new version beside it as
# <file>.new for you to diff. The format specs are meant to be customised, so
# your edits are never silently overwritten.

set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_REL=".agents/.agent-lifecycle-skills.manifest"

MODE="install"
DRY=0
DEST=""

while [ $# -gt 0 ]; do
  case "$1" in
    --update)  MODE="update" ;;
    --dry-run) DRY=1 ;;
    -h|--help)
      sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    -*) echo "unknown option: $1" >&2; exit 1 ;;
    *)  DEST="$1" ;;
  esac
  shift
done

if [ -z "$DEST" ]; then
  echo "usage: $0 [--update] [--dry-run] /path/to/project" >&2
  exit 1
fi
if [ ! -d "$DEST" ]; then
  echo "not a directory: $DEST" >&2
  exit 1
fi

FILES="docs/specs/README.md
docs/specs/_TEMPLATE.md
docs/sessions/README.md
docs/sessions/_TEMPLATE.md
.agents/skills/spec/SKILL.md
.agents/skills/wrap/SKILL.md
.claude/skills/spec/SKILL.md
.claude/skills/wrap/SKILL.md"

# sha256 that works on both macOS and Linux
hash_of() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    sha256sum "$1" | cut -d' ' -f1
  fi
}

recorded_hash() {   # $1 = relative path; empty if absent from the manifest
  [ -f "$DEST/$MANIFEST_REL" ] || return 0
  awk -v p="$1" '$2 == p { print $1; exit }' "$DEST/$MANIFEST_REL"
}

say() { printf '  %-9s %s\n' "$1" "$2"; }

do_cp() { [ "$DRY" -eq 1 ] || { mkdir -p "$(dirname "$2")"; cp "$1" "$2"; }; }

if [ "$MODE" = "install" ]; then
  echo "Installing /spec and /wrap into $DEST"
else
  echo "Updating /spec and /wrap in $DEST"
  if [ ! -f "$DEST/$MANIFEST_REL" ]; then
    echo "  note: no manifest found (installed before update support existed)."
    echo "        Every existing file is treated as customised, so you will get"
    echo "        .new files to diff rather than in-place updates."
  fi
fi
[ "$DRY" -eq 1 ] && echo "  (dry run — nothing will be written)"

echo "$FILES" | while IFS= read -r rel; do
  [ -n "$rel" ] || continue
  src="$SRC/$rel"
  dst="$DEST/$rel"

  if [ ! -e "$dst" ]; then
    do_cp "$src" "$dst"; say create "$rel"; continue
  fi

  if [ "$MODE" = "install" ]; then
    say skip "$rel (already exists)"; continue
  fi

  now="$(hash_of "$dst")"
  new="$(hash_of "$src")"
  was="$(recorded_hash "$rel")"

  if [ "$now" = "$new" ]; then
    say "current" "$rel"
  elif [ -n "$was" ] && [ "$now" = "$was" ]; then
    do_cp "$src" "$dst"; say update "$rel"
  else
    do_cp "$src" "$dst.new"; say "yours" "$rel (kept — new version at $rel.new)"
  fi
done

# AGENTS.md is the project's own file: only ever appended to, never rewritten.
if [ -f "$DEST/AGENTS.md" ] && grep -q "Specs and session wraps" "$DEST/AGENTS.md" 2>/dev/null; then
  say skip "AGENTS.md (already wired up)"
else
  [ "$DRY" -eq 1 ] || sed '1,/^-->$/d' "$SRC/AGENTS.md.snippet" >> "$DEST/AGENTS.md"
  say append "AGENTS.md"
fi

# Record what this run installed, so the next update can tell your edits from ours.
if [ "$DRY" -eq 0 ]; then
  mkdir -p "$DEST/.agents"
  SRC_VER="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  {
    echo "# agent-lifecycle-skills — generated by install.sh, do not edit"
    echo "# source $SRC_VER   installed $(date +%Y-%m-%d)"
    echo "$FILES" | while IFS= read -r rel; do
      [ -n "$rel" ] || continue
      [ -f "$DEST/$rel" ] && echo "$(hash_of "$DEST/$rel")  $rel"
    done
  } > "$DEST/$MANIFEST_REL"
fi

if [ "$MODE" = "install" ]; then
cat <<'EOM'

Done.

  Claude Code, Cursor   /spec   /wrap
  Codex CLI             $spec   $wrap
  Anything else         AGENTS.md tells it what to do

Next:
  1. Fill in the Verification commands block appended to AGENTS.md — the build
     and test commands for this project. Specs reference them.
  2. Read docs/specs/README.md and docs/sessions/README.md and adjust them to
     your taste; they are the single source of truth for the two formats.
  3. Commit the lot.
EOM
else
cat <<'EOM'

Done. Anything marked "yours" was left untouched; diff it against the .new file
beside it when you want the newer wording:

  git diff --no-index docs/specs/README.md docs/specs/README.md.new

Delete the .new files once you are happy.
EOM
fi
