#!/usr/bin/env bash
# agent-lifecycle-skills — sync /spec and /wrap into a project.
# https://github.com/imanassi/agent-lifecycle-skills
#
#   ./sync.sh /path/to/project              install, or update if already there
#   ./sync.sh --dry-run /path/to/project    show what would change, write nothing
#
# The mode is detected, not chosen. A project with none of the files gets a fresh
# install. A project that already has them gets an update.
#
# Updating is conservative: files you have not edited are refreshed in place, and
# files you HAVE edited are left exactly as they are, with the newer version written
# beside them as <file>.new for you to diff. The two format specs are meant to be
# customised, so nothing you wrote is ever overwritten.

set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_REL=".agents/.agent-lifecycle-skills.manifest"

DRY=0
DEST=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run|-n) DRY=1 ;;
    -h|--help)    sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*)           echo "unknown option: $1" >&2; exit 1 ;;
    *)            DEST="$1" ;;
  esac
  shift
done

[ -n "$DEST" ]  || { echo "usage: $0 [--dry-run] /path/to/project" >&2; exit 1; }
[ -d "$DEST" ]  || { echo "not a directory: $DEST" >&2; exit 1; }

FILES="docs/specs/README.md
docs/specs/_TEMPLATE.md
docs/sessions/README.md
docs/sessions/_TEMPLATE.md
.agents/skills/spec/SKILL.md
.agents/skills/wrap/SKILL.md
.claude/skills/spec/SKILL.md
.claude/skills/wrap/SKILL.md"

hash_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
  else sha256sum "$1" | cut -d' ' -f1; fi
}

recorded_hash() {
  [ -f "$DEST/$MANIFEST_REL" ] || return 0
  awk -v p="$1" '$2 == p { print $1; exit }' "$DEST/$MANIFEST_REL"
}

say()   { printf '  %-9s %s\n' "$1" "$2"; }
do_cp() { [ "$DRY" -eq 1 ] || { mkdir -p "$(dirname "$2")"; cp "$1" "$2"; }; }

# ---- detect the mode -------------------------------------------------------
MODE="install"
for rel in $FILES; do
  [ -e "$DEST/$rel" ] && { MODE="update"; break; }
done
[ -f "$DEST/$MANIFEST_REL" ] && MODE="update"

if [ "$MODE" = "install" ]; then
  echo "Installing /spec and /wrap into $DEST"
else
  echo "Already installed — updating $DEST"
  if [ ! -f "$DEST/$MANIFEST_REL" ]; then
    echo "  note: no manifest (installed before sync.sh existed), so every file that"
    echo "        differs is treated as customised — you get .new files to diff"
    echo "        rather than in-place changes. Only happens once."
  fi
fi
[ "$DRY" -eq 1 ] && echo "  (dry run — nothing will be written)"

n_create=0; n_update=0; n_yours=0; n_current=0

# The manifest records the UPSTREAM version each file was last synced from — never
# what happens to be on disk. Recording the disk state would make an edited file look
# pristine on the next run, and the run after that would overwrite it.
MF="$(mktemp)"
trap 'rm -f "$MF"' EXIT

for rel in $FILES; do
  src="$SRC/$rel"; dst="$DEST/$rel"

  new="$(hash_of "$src")"

  if [ ! -e "$dst" ]; then
    do_cp "$src" "$dst"; say create "$rel"; n_create=$((n_create+1))
    echo "$new  $rel" >> "$MF"; continue
  fi

  now="$(hash_of "$dst")"; was="$(recorded_hash "$rel")"

  if [ "$now" = "$new" ]; then
    say current "$rel"; n_current=$((n_current+1))
    echo "$new  $rel" >> "$MF"
  elif [ -n "$was" ] && [ "$now" = "$was" ]; then
    do_cp "$src" "$dst"; say update "$rel"; n_update=$((n_update+1))
    echo "$new  $rel" >> "$MF"
  else
    do_cp "$src" "$dst.new"; say yours "$rel  →  new version at $rel.new"
    n_yours=$((n_yours+1))
    # Keep the old baseline. Refreshing it here would mark this edited file as
    # pristine and the next run would silently overwrite it.
    [ -n "$was" ] && echo "$was  $rel" >> "$MF"
  fi
done

# AGENTS.md belongs to the project: only ever appended to, never rewritten.
if [ -f "$DEST/AGENTS.md" ] && grep -q "Specs and session wraps" "$DEST/AGENTS.md" 2>/dev/null; then
  say skip "AGENTS.md (already wired up)"
else
  [ "$DRY" -eq 1 ] || sed '1,/^-->$/d' "$SRC/AGENTS.md.snippet" >> "$DEST/AGENTS.md"
  say append "AGENTS.md"
fi

# Record what this run put there, so the next sync can tell your edits from ours.
if [ "$DRY" -eq 0 ]; then
  mkdir -p "$DEST/.agents"
  SRC_VER="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  {
    echo "# agent-lifecycle-skills — generated by sync.sh, do not edit"
    echo "# source $SRC_VER   synced $(date +%Y-%m-%d)"
    echo "# each hash is the UPSTREAM version that file was last synced from"
    cat "$MF"
  } > "$DEST/$MANIFEST_REL"
fi

echo
if [ "$MODE" = "install" ]; then
cat <<'EOM'
Done.

  Claude Code, Cursor   /spec   /wrap
  Codex CLI             $spec   $wrap
  Anything else         AGENTS.md tells it what to do

Next:
  1. Fill in the Verification commands block appended to AGENTS.md — the build
     and test commands for this project. Specs reference them.
  2. Read docs/specs/README.md and docs/sessions/README.md and adjust them to
     your taste; they are the single source of truth for the two formats.
  3. Commit the lot.
EOM
elif [ "$n_yours" -gt 0 ]; then
  echo "Done — $n_update updated, $n_current already current, $n_yours left as yours."
  echo
  echo "Your $n_yours edited file(s) were not touched. Diff each against its .new:"
  echo
  echo "  git diff --no-index <file> <file>.new"
  echo
  echo "Then delete the .new files. (They are gitignored.)"
else
  echo "Done — $n_update updated, $n_current already current, nothing of yours touched."
fi
